config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#home'

  resources :lists, only: [:index, :show, :create, :destroy ] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  has_one_attached :photo

  validates :comment, presence: true, length: { minimum: 6 }
  validates :list, presence: true
  validates :movie, uniqueness: { scope: :list_id} #the movie must be unique with the scope of the list_id
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_many_attached :photo

  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, uniqueness: true
  validates :title, :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :find_bookmark, only: :destroy
  before_action :find_list, only: [:new, :create ]

  # def new
  #   @list = List.find(params[:list_id])
  #   @bookmark = Bookmark.new
  # end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
      if @bookmark.save
        redirect_to list_path(@list)
      else
        render 'lists/show'
      end
  end

  def destroy
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def find_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def find_list
    @list = List.find(params[:list_id])
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def home
    @list = List.new
  end

  def index
    @lists = List.all
    @list = List.new
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end

  def create
    @lists = List.all
    @list = List.new(list_params)
      if @list.save
        redirect_to lists_path
      else
        render 'index' # keeps staying there
      end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path
  end

  private
    def list_params
      params.require(:list).permit(:name, photo: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="container">
<h1>Add new movie to your <%= @list.name %> list</h1>

<%= simple_form_for [ @list, @bookmark ] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.button :submit, class: "btn btn-primary" %> <%= link_to "Cancel", lists_path %>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div id="navbar">
    <div class="submit-container">
      <ul>
        <li><%= link_to "Home", lists_path  %></li>

        <li> <%= simple_form_for(@list) do |f| %>
          <%= f.input :name, class:"input-size", placeholder:" List name",  label: false %>
          <%= f.submit 'Add to list', class:"submit-list" %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>



    <%= yield %>

<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="https://www.instagram.com/anxious.likeappa"><i class="fab fa-instagram"></i></a>
  </div>
</div>

  </body>
</html>

app/views/lists/home.html.erb
<div class="hero-image">
  <div class="hero-text">
  <h1> Movie time </h1>
    <p>Let's create lists!:D</p>
    <%= link_to "Let's start", lists_path, class: "home-button" %>
  </div>
 </div>

<%#
<h1 data-controller="typed-js" class="home-typed"></h1> %>

app/views/lists/index.html.erb
<div class="new-section-list"> Your movie lists </div>

<div class="container">
  <div class="cards">
    <% @lists.each do |list| %>

        <div class="list-card-category">
          <%= link_to list_path(list) do %>
            <%= list.name %></h1> <%= link_to "(X)", list_path(list), method: :delete, data: { confirm: "Are you sure you want to delete this list?"} %>
            <div>
            </div>

          <% end %>

        </div>
    <% end %>
  </div>
</div>

app/views/lists/show.html.erb
<h1 class="show-page-title"><%= @list.name.capitalize %></h1>
<div class="container">
  <div class="container">
    <div class="cards">
     <% @list.bookmarks.each do |bookmark| %>
      <div class="flip-card">
        <div class="flip-card-inner">

          <div class="flip-card-front">
            <%= image_tag "https://image.tmdb.org/t/p/w200/#{bookmark.movie.poster_url}", class: "img-show" %>
          </div>

          <div class="flip-card-back">
            <h2 class="show-card-title"><%= bookmark.movie.title %> <%= link_to "X", bookmark_path(bookmark), method: :delete, data: { confirm: "Are you sure you want to delete this movie?"}, class:"show-delete-button" %></h2>

            <p>Rating:<%= bookmark.movie.rating %>/10</p>
            <p class="movie-overview"><%= bookmark.movie.overview %></p>
            <p class="show-comment">Comment:</p>
            <p class="user-show-comment"><%= bookmark.comment %></p>
          </div>

        </div>
      </div>
      <% end %>
    </div>
  </div>



  <h3 class="new-section" >Add new movie to your list</h3>
  <%= simple_form_for [ @list, @bookmark ] do |f| %>
  <%= f.association :movie, prompt: "Please Select",  label: false %>
  <%= f.input :comment, placeholder:"Comment ",  label: false %>
  <%# <%= f.input :photo, as: :file %>
  <%= f.button :submit, class: "home-button" %>
  <p><%= link_to "Cancel", lists_path, class:"cancel-button" %></p>
<% end %>

</div>
</div>